In [8]:
import torch

In [2]:
## all packages of torch
## kaggle already has Cuda installed else we need cuda
!pip list

Package                                  Version
---------------------------------------- -------------------
absl-py                                  1.4.0
accelerate                               0.29.3
access                                   1.1.9
affine                                   2.4.0
aiobotocore                              2.12.3
aiofiles                                 22.1.0
aiohttp                                  3.9.1
aiohttp-cors                             0.7.0
aioitertools                             0.11.0
aiorwlock                                1.3.0
aiosignal                                1.3.1
aiosqlite                                0.19.0
albumentations                           1.4.0
alembic                                  1.13.1
altair                                   5.3.0
annotated-types                          0.6.0
annoy                                    1.17.3
anyio                                    4.2.0
apache-beam                          

## Tensors
- A torch, tensor is a multi - dimensional matrix containing elements of a sgle data type
- Similar to numpy arrays, but full of things that will make them work better GPUs (vs regular CPU)
- default data type of float 32
- More suitable for deep learning than a numpy array

In [4]:
import numpy as np

## Lists

In [1]:
my_list=[1,2,3,4]
my_list

[1, 2, 3, 4]

In [2]:
my_list=[[1,2,3,4],[2,3,4]]
my_list

[[1, 2, 3, 4], [2, 3, 4]]

## Numpy arrays

In [6]:
np1= np.random.rand(3,4)
np1

array([[0.79340014, 0.61484902, 0.73729666, 0.54740491],
       [0.46863929, 0.42652056, 0.86074241, 0.07994677],
       [0.89928961, 0.69839018, 0.91280309, 0.69224312]])

In [7]:
np1.dtype

dtype('float64')

## Tensors

In [9]:
# 2d tensor
tensor_2d= torch.rand(3,4)
tensor_2d

tensor([[0.8288, 0.3967, 0.2720, 0.2458],
        [0.5715, 0.1530, 0.8508, 0.6902],
        [0.3316, 0.6477, 0.4056, 0.8677]])

In [11]:
# 3d tensor
tensor_3d= torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
## Create tensor out of numpy array
my_tensor=torch.tensor(np1)
my_tensor

tensor([[0.7934, 0.6148, 0.7373, 0.5474],
        [0.4686, 0.4265, 0.8607, 0.0799],
        [0.8993, 0.6984, 0.9128, 0.6922]], dtype=torch.float64)

In [13]:
tensor_2d.dtype

torch.float32

**Further reference- https://pytorch.org/docs/stable/tensors.html**